[package]
name = "burge-proj"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.127"
glium = "0.26.0-alpha3"
glutin = "0.26.0-alpha3"
image = "0.25.2"

[dependencies.uuid]
version = "1.10.0"
features = ["v4", "fast-rng", "macro-diagnostics"]

